version: 2
updates:
  - package-ecosystem: npm
    directory: /vue-toutiao
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
